# Supabase Configuration File
# https://supabase.com/docs/guides/local-development/managing-config

# Edge Functions Configuration
[functions.elevenlabs-webhook]
verify_jwt = false  # Make webhook public for ElevenLabs

[functions.sync-elevenlabs-data]
verify_jwt = true   # Keep sync function protected

[functions.agents-analytics]
verify_jwt = true   # Keep analytics protected